// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  companyId: __t.u64().primaryKey().name("company_id"),
  agentAutoJoin: __t.bool().name("agent_auto_join"),
  postSummaries: __t.bool().name("post_summaries"),
  notifyRepeatedTopics: __t.bool().name("notify_repeated_topics"),
  topicSensitivity: __t.string().name("topic_sensitivity"),
  updatedAt: __t.u64().name("updated_at"),
});
