// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "./accept_invite_reducer";
import CancelMeetingReducer from "./cancel_meeting_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateMeetingReducer from "./create_meeting_reducer";
import EndMeetingReducer from "./end_meeting_reducer";
import JoinChannelReducer from "./join_channel_reducer";
import LeaveCompanyReducer from "./leave_company_reducer";
import LogoutReducer from "./logout_reducer";
import MarkSummaryIndexedReducer from "./mark_summary_indexed_reducer";
import OpenDmReducer from "./open_dm_reducer";
import PostAgentMessageReducer from "./post_agent_message_reducer";
import RegenerateInviteTokenReducer from "./regenerate_invite_token_reducer";
import RegisterCompanyReducer from "./register_company_reducer";
import RemoveUserReducer from "./remove_user_reducer";
import RevokeInviteReducer from "./revoke_invite_reducer";
import SendMessageReducer from "./send_message_reducer";
import StartMeetingReducer from "./start_meeting_reducer";
import StoreMeetingSummaryReducer from "./store_meeting_summary_reducer";
import UpdateCompanyNameReducer from "./update_company_name_reducer";
import UpdateCompanySettingsReducer from "./update_company_settings_reducer";
import UpdatePasswordReducer from "./update_password_reducer";
import UpdateUserProfileReducer from "./update_user_profile_reducer";
import UpdateUserRoleReducer from "./update_user_role_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChannelRow from "./channel_table";
import ChannelMemberRow from "./channel_member_table";
import CompanyRow from "./company_table";
import CompanySettingRow from "./company_setting_table";
import DmConversationRow from "./dm_conversation_table";
import MeetingRow from "./meeting_table";
import MeetingParticipantRow from "./meeting_participant_table";
import MeetingSummaryRow from "./meeting_summary_table";
import MessageRow from "./message_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  channel: __table({
    name: 'channel',
    indexes: [
      { accessor: 'id', name: 'channel_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'channel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChannelRow),
  channelMember: __table({
    name: 'channel_member',
    indexes: [
    ],
    constraints: [
    ],
  }, ChannelMemberRow),
  company: __table({
    name: 'company',
    indexes: [
      { accessor: 'id', name: 'company_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'company_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CompanyRow),
  companySetting: __table({
    name: 'company_setting',
    indexes: [
      { accessor: 'companyId', name: 'company_setting_company_id_idx_btree', algorithm: 'btree', columns: [
        'companyId',
      ] },
    ],
    constraints: [
      { name: 'company_setting_company_id_key', constraint: 'unique', columns: ['companyId'] },
    ],
  }, CompanySettingRow),
  dmConversation: __table({
    name: 'dm_conversation',
    indexes: [
      { accessor: 'id', name: 'dm_conversation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dm_conversation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DmConversationRow),
  meeting: __table({
    name: 'meeting',
    indexes: [
      { accessor: 'id', name: 'meeting_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'meeting_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingRow),
  meetingParticipant: __table({
    name: 'meeting_participant',
    indexes: [
    ],
    constraints: [
    ],
  }, MeetingParticipantRow),
  meetingSummary: __table({
    name: 'meeting_summary',
    indexes: [
      { accessor: 'id', name: 'meeting_summary_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'meeting_summary_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingSummaryRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'id', name: 'user_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_invite", AcceptInviteReducer),
  __reducerSchema("cancel_meeting", CancelMeetingReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_meeting", CreateMeetingReducer),
  __reducerSchema("end_meeting", EndMeetingReducer),
  __reducerSchema("join_channel", JoinChannelReducer),
  __reducerSchema("leave_company", LeaveCompanyReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("mark_summary_indexed", MarkSummaryIndexedReducer),
  __reducerSchema("open_dm", OpenDmReducer),
  __reducerSchema("post_agent_message", PostAgentMessageReducer),
  __reducerSchema("regenerate_invite_token", RegenerateInviteTokenReducer),
  __reducerSchema("register_company", RegisterCompanyReducer),
  __reducerSchema("remove_user", RemoveUserReducer),
  __reducerSchema("revoke_invite", RevokeInviteReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("start_meeting", StartMeetingReducer),
  __reducerSchema("store_meeting_summary", StoreMeetingSummaryReducer),
  __reducerSchema("update_company_name", UpdateCompanyNameReducer),
  __reducerSchema("update_company_settings", UpdateCompanySettingsReducer),
  __reducerSchema("update_password", UpdatePasswordReducer),
  __reducerSchema("update_user_profile", UpdateUserProfileReducer),
  __reducerSchema("update_user_role", UpdateUserRoleReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

