// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  companyId: __t.u64().name("company_id"),
  title: __t.string(),
  description: __t.option(__t.string()),
  scheduledAt: __t.u64().name("scheduled_at"),
  startedAt: __t.option(__t.u64()).name("started_at"),
  endedAt: __t.option(__t.u64()).name("ended_at"),
  livekitRoomName: __t.string().name("livekit_room_name"),
  createdBy: __t.u64().name("created_by"),
  status: __t.string(),
});
