// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  meetingId: __t.u64().name("meeting_id"),
  companyId: __t.u64().name("company_id"),
  summaryText: __t.string().name("summary_text"),
  keyDecisions: __t.string().name("key_decisions"),
  actionItems: __t.string().name("action_items"),
  generatedAt: __t.u64().name("generated_at"),
  pineconeIndexed: __t.bool().name("pinecone_indexed"),
});
