// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  id: __t.u64(),
  companyId: __t.u64(),
  name: __t.string(),
  createdBy: __t.u64(),
  createdAt: __t.u64(),
  isPrivate: __t.bool(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelMember = __t.object("ChannelMember", {
  channelId: __t.u64(),
  userId: __t.u64(),
  joinedAt: __t.u64(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const Company = __t.object("Company", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.u64(),
  adminUserId: __t.u64(),
});
export type Company = __Infer<typeof Company>;

export const CompanySetting = __t.object("CompanySetting", {
  companyId: __t.u64(),
  agentAutoJoin: __t.bool(),
  postSummaries: __t.bool(),
  notifyRepeatedTopics: __t.bool(),
  topicSensitivity: __t.string(),
  updatedAt: __t.u64(),
});
export type CompanySetting = __Infer<typeof CompanySetting>;

export const DmConversation = __t.object("DmConversation", {
  id: __t.u64(),
  companyId: __t.u64(),
  userAId: __t.u64(),
  userBId: __t.u64(),
  createdAt: __t.u64(),
});
export type DmConversation = __Infer<typeof DmConversation>;

export const Meeting = __t.object("Meeting", {
  id: __t.u64(),
  companyId: __t.u64(),
  title: __t.string(),
  description: __t.option(__t.string()),
  scheduledAt: __t.u64(),
  startedAt: __t.option(__t.u64()),
  endedAt: __t.option(__t.u64()),
  livekitRoomName: __t.string(),
  createdBy: __t.u64(),
  status: __t.string(),
  agentEnabled: __t.option(__t.bool()),
});
export type Meeting = __Infer<typeof Meeting>;

export const MeetingParticipant = __t.object("MeetingParticipant", {
  meetingId: __t.u64(),
  userId: __t.u64(),
  joinedAt: __t.option(__t.u64()),
});
export type MeetingParticipant = __Infer<typeof MeetingParticipant>;

export const MeetingSummary = __t.object("MeetingSummary", {
  id: __t.u64(),
  meetingId: __t.u64(),
  companyId: __t.u64(),
  summaryText: __t.string(),
  keyDecisions: __t.string(),
  actionItems: __t.string(),
  generatedAt: __t.u64(),
  pineconeIndexed: __t.bool(),
});
export type MeetingSummary = __Infer<typeof MeetingSummary>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  companyId: __t.u64(),
  senderId: __t.u64(),
  content: __t.string(),
  sentAt: __t.u64(),
  channelType: __t.string(),
  channelId: __t.u64(),
  isAgentMessage: __t.bool(),
});
export type Message = __Infer<typeof Message>;

export const User = __t.object("User", {
  id: __t.u64(),
  identity: __t.option(__t.string()),
  companyId: __t.u64(),
  email: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  inviteToken: __t.option(__t.string()),
  isActive: __t.bool(),
  createdAt: __t.u64(),
});
export type User = __Infer<typeof User>;

