// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  companyId: __t.u64().name("company_id"),
  senderId: __t.u64().name("sender_id"),
  content: __t.string(),
  sentAt: __t.u64().name("sent_at"),
  channelType: __t.string().name("channel_type"),
  channelId: __t.u64().name("channel_id"),
  isAgentMessage: __t.bool().name("is_agent_message"),
});
