// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "../accept_invite_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateMeetingReducer from "../create_meeting_reducer";
import EndMeetingReducer from "../end_meeting_reducer";
import JoinChannelReducer from "../join_channel_reducer";
import LogoutReducer from "../logout_reducer";
import MarkSummaryIndexedReducer from "../mark_summary_indexed_reducer";
import OpenDmReducer from "../open_dm_reducer";
import PostAgentMessageReducer from "../post_agent_message_reducer";
import RegenerateInviteTokenReducer from "../regenerate_invite_token_reducer";
import RegisterCompanyReducer from "../register_company_reducer";
import RemoveUserReducer from "../remove_user_reducer";
import RevokeInviteReducer from "../revoke_invite_reducer";
import SendMessageReducer from "../send_message_reducer";
import StartMeetingReducer from "../start_meeting_reducer";
import StoreMeetingSummaryReducer from "../store_meeting_summary_reducer";
import UpdateCompanyNameReducer from "../update_company_name_reducer";
import UpdateCompanySettingsReducer from "../update_company_settings_reducer";
import UpdateUserRoleReducer from "../update_user_role_reducer";

export type AcceptInviteParams = __Infer<typeof AcceptInviteReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateMeetingParams = __Infer<typeof CreateMeetingReducer>;
export type EndMeetingParams = __Infer<typeof EndMeetingReducer>;
export type JoinChannelParams = __Infer<typeof JoinChannelReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type MarkSummaryIndexedParams = __Infer<typeof MarkSummaryIndexedReducer>;
export type OpenDmParams = __Infer<typeof OpenDmReducer>;
export type PostAgentMessageParams = __Infer<typeof PostAgentMessageReducer>;
export type RegenerateInviteTokenParams = __Infer<typeof RegenerateInviteTokenReducer>;
export type RegisterCompanyParams = __Infer<typeof RegisterCompanyReducer>;
export type RemoveUserParams = __Infer<typeof RemoveUserReducer>;
export type RevokeInviteParams = __Infer<typeof RevokeInviteReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type StartMeetingParams = __Infer<typeof StartMeetingReducer>;
export type StoreMeetingSummaryParams = __Infer<typeof StoreMeetingSummaryReducer>;
export type UpdateCompanyNameParams = __Infer<typeof UpdateCompanyNameReducer>;
export type UpdateCompanySettingsParams = __Infer<typeof UpdateCompanySettingsReducer>;
export type UpdateUserRoleParams = __Infer<typeof UpdateUserRoleReducer>;

